### ISSUE TITLE
Throw by default?

### ISSUE THREAD

**Issue by tomek-he-him** [ericelliott/rfx#10]
I was quite surprized that the interface doesn’t throw a TypeError when I called it with invalid parameters.

Then I [read on](https://github.com/ericelliott/rfx/blob/c76f9626708e98c86b1c511a68c22a17954b314d/test/flow-logic/index.js#L20-L34) – alright, I can specify an `onError` callback. Fair enough, I think it’s the right thing to do for our API.

But if I don’t specify an `onError`, _rfx_ should definitely throw. Or else we’ll have [promises](http://jamesknelson.com/are-es6-promises-swallowing-your-errors/) again!

**Comment by ericelliott** [comment]
Maybe.

**Comment by tomek-he-him** [comment]
Do you see any drawbacks with throwing by default?

As far as testing is concerned – or manual error handling – `onError` is the perfect thing. But if I don’t handle the error in any way, the program should crash. `throw` is the perfect tool for that.

**Comment by ericelliott** [comment]
I'm willing to give it a try and see how it works on production servers. I was worried that it might open up DOS vulnerabilities on servers, but maybe that can be mitigated by using a really broad input type definition for functions that take user input, and then tightening up the types after the input has been validated.

**Comment by tomek-he-him** [comment]
Yeah, that’s definitely a way to go for the user.

As well as that – as I glimpsed through your code I noticed that you’re [basing behavior off `NODE_ENV`](https://github.com/ericelliott/rfx/blob/c76f9626708e98c86b1c511a68c22a17954b314d/source/index.js#L23) – we can switch the throwing off by default. We can make it opt-in and only switch it on when `NODE_ENV && NODE_ENV === 'development'`.

**Comment by ericelliott** [comment]
Ooh, I really like that. PR? =)
