### ISSUE TITLE
roadmap question: rtype builtins

### ISSUE THREAD

**Issue by jokeyrhyme** [ericelliott/rfx#16]
I was thinking about taking a crack at this, but I'm not sure I understand what this bullet point is, exactly.

I assume this is pre-parser, and is for building predicates in JavaScript.

e.g.

``` js
import  { isAny, isArray, isBoolean, isFunction, isNumber, isObject, isString, isVoid } from 'rfx-builtins';
import  rfx from 'rfx';

const type = (param, otherParam, options) => (
  isString(param) &&
  isArray(otherParam) &&
  /* ... (Type checking optional and neatly separated!) */
);

export const myFunction = (param, otherParam, options) => {
  /* (Just business logic.) */
}

export const myInterface = rfx({
  type,
  fn: myFunction
});
```

Is this pretty much what you were expecting? The exported predicate names can't literally be the same as the built-in names, so I just went with a conventional (to me) `is...` prefix.

Also, have you seen this type checking library? https://github.com/enricomarino/is
Would it be appropriate to just extract the builtin-related functions from that (it's also MIT licensed)?

**Comment by jokeyrhyme** [comment]
Also, that "is" module has no dependencies, and minifies down to 6.4KB. Just FYI.

**Comment by ericelliott** [comment]
Sounds like you've got the basic idea, but this stuff should be implemented in the [rtype repo](https://github.com/ericelliott/rtype). I think we can get much lower than 6.4KB if we just extract the stuff we need from `is()`. If we go that route, that should also be its own npm module, unless you can find one that already exists that just supplies predicates for builtin JS constructors.

**Comment by ericelliott** [comment]
On second thought.... I'm fine with an `is()` dependency for now. =) Don't bother extracting yet. Let's make it work first, see how the spec evolves, and extract later if we need to optimize it.

**Comment by Mouvedia** [comment]
For `isString` you should use [isstring](https://www.npmjs.org/package/isstring). It's cross-browser and has been tested. Check the [max](http://isstring.surge.sh/) for the commented version.

disclaimer: I am the author

**Comment by jokeyrhyme** [comment]
@Mouvedia the PR where the actual implementation is happening is over at https://github.com/ericelliott/rtype/issues/40

Regarding isstring:
- it's impressive that you capture browser globals to tamper-proof them, but rfx by default doesn't do anything in production mode where tampering is most likely
- the implementation for this PR so far is here: https://github.com/enricomarino/is/blob/master/index.js#L712 which covers the string literal versus `String()` constructor edge case that isstring covers
- do we anticipate running rfx with a project that has to run on IE < 5.5 ?

**Comment by jokeyrhyme** [comment]
@Mouvedia Just remembered that rfx is written in ES2015, and transpiled to ES5, which won't run in ES3-only environments or worse.

**Comment by Mouvedia** [comment]
Your implementation wouldn't work on pre-blink Opera for example. When I read "Access type metadata inside your program at runtime" I thought you were planning to use rfx directly in the browser, my bad you can ignore my suggestion then.

**Comment by jokeyrhyme** [comment]
Actually, it is my understanding that rfx _could_ be used directly in the browser. However, by default it isn't active during production: https://github.com/ericelliott/rfx#error-handling

But if development and/or testing of a project that uses rfx were taking place in pre-blink Opera, then there's probably value in using isstring.

**Comment by ericelliott** [comment]
> do we anticipate running rfx with a project that has to run on IE < 5.5 ?

No. Don't worry about anything before IE11. Microsoft drops support for all IE < 11 in January.

**Comment by ericelliott** [comment]
> Actually, it is my understanding that rfx could be used directly in the browser.

Yes, transpiled to ES5.

**Comment by tomek-he-him** [comment]
> Microsoft drops support for all IE < 11 in January.

Wow! Didn’t know that! :+1: :+1: :+1:

**Comment by tomek-he-him** [comment]
@ericelliott However, to be accurate, it’s not quite that good yet: http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx.

IE 10 has support until Windows Server 2012 dies.

IE 9 has support until Windows Vista and Windows Server 2008 dies.

(Though I don’t see any major reason for supporting a _browser_ on a _server_. So it should be fine to ignore that use case.)

**Comment by tomek-he-him** [comment]
> until Windows Vista […] dies

According to http://gs.statcounter.com/#os-ww-monthly-201410-201510 it’s still being used by ~1.5% online users worldwide. That may be a show-stopper for some companies.

**Comment by ericelliott** [comment]
That old blog post has been superceded by [this announcement](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support). I wasn't kidding. All versions prior to IE11 will have support discontinued in January.

**Comment by tomek-he-him** [comment]
Yeah, I know you wasn’t kidding – but I guess they’ve deliberately written it so that it sounds like IE <11 dies. But in the announcement you’ve linked to they say: “Beginning January 12, 2016, only the most current version of Internet Explorer **available for a supported operating system** will receive technical supports and security updates.”.

And unfortunately Windows Vista is still supported [until April 2017](http://windows.microsoft.com/en-us/windows/lifecycle).

**Comment by replete** [comment]
Yeah, everyone is excited about 'IE 11 dying' but that's not really the case. There will be users.

**Comment by ericelliott** [comment]
@tomekwi Maybe nobody is communicating Vista & Pre IE 11 support to the IE team, because IE 11 is the ONLY legacy IE being explicitly mentioned for ongoing support anywhere I can find, and I assume that means all their maintenance focus will be on Edge and IE 11.

> Internet Explorer 11 is the last version of Internet Explorer, and will continue to receive security updates, compatibility fixes, and technical support on Windows 7, Windows 8.1, and Windows 10.

See also [The End is Near](https://technet.microsoft.com/en-us/browser).

**Comment by ericelliott** [comment]
IE 11 will still be supported. **Don't count on any support for any IE before 11.**

**Comment by ericelliott** [comment]
Windows Vista [Mainstream Support ended in 2012](http://windows.microsoft.com/en-us/windows/lifecycle).

**Comment by tomek-he-him** [comment]
Anyway, :+1: to not supporting IE <11. How about mentioninig it in the docs?

**Comment by ericelliott** [comment]
Closing because type check implementations are out of scope for rfx.

rfx is just a way to tag interfaces with type information. See rtype for actual type checking code.
