### ISSUE TITLE
Similar initiatives

### ISSUE THREAD

**Issue by josdejong** [ericelliott/rfx#18]
@ericelliott I heard about your initiative for rfx via your latest blog. I've been working on similar solutions:

https://github.com/josdejong/typed-function
https://github.com/josdejong/ducktype

Not sure if/how there there is a way to collaborate here and coordinate these efforts.  At least it's good to be aware of each others work :) It makes sense for example if we could use the same syntax for type notations.

**Comment by ericelliott** [comment]
See also: https://github.com/ericelliott/rtype/issues/47

**Comment by tomek-he-him** [comment]
@josdejong how nice to see you around here! Perhaps – if you had time – you could work together with @jokeyrhyme on our tokenizer?

@ericelliott, @josdejong is somewhat an expert in writing parsers and things. He’s the mastermind of http://mathjs.org/.

**Comment by josdejong** [comment]
Thanks, I will check out the discussion at ericelliott/rtype#47.
