### ISSUE TITLE
compare with Node Machines

### ISSUE THREAD

**Issue by billiegoose** [ericelliott/rfx#19]
Just saw this, it's cool! (I'm also hacking on a similar pet project.) I thought you might like looking at the [Node Machine](http://node-machine.org/spec/machine) project. It looks like it has some similar goals and might be worth stealing some ideas. :stuck_out_tongue_winking_eye:

**Comment by ericelliott** [comment]
Yep, I'm aware of Node Machines. I think we could pretty easily write an adaptor for them.
