### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by jacoborus** [ericelliott/rfx#20]
I'm loving the rfx concept, but I don't get how we are going to minificate our files. As you mentioned [here](https://github.com/ericelliott/rfx/issues/16#issuecomment-160576570) this is for use directly in the browser, also we are writing description, doc and example as strings in the rfx argument object. Now the question is obvious: how to uglify this?

I would like to propose another syntax following [this snippet style](https://github.com/ericelliott/rfx/issues/8#issuecomment-156593142):

``` js
/**
 * A one-line description of the function’s purpose
 *
 * A nice multiline description here. Blabla bla bla blablabla. More docs.
 * I don't think injected vars are so important here
 *
 // An amazing example
 // not using asterisks here improves code readability
 // and could help the parser differentiating the example
 */
rfx(
  rtype`
    myFunction(
      param: String,
      options?: {x: Number, y: Number},
    ): Boolean
  `,
  myFunction () {}
)
```

Also, I think this is easier to read than the other examples, and it should be easy to parse for documentation tools too.

**Comment by ericelliott** [comment]
That's missing the point of `rfx`. The whole point is to make all of the metadata available in the code at runtime so that you can get at it using runtime reflection. For more on why we might want to do that, see the Visual IDE's section of ["The Future of Programming"](http://www.sitepoint.com/future-programming-webassembly-life-after-javascript/).

A smart compiler should be able to strip the `rfx` calls entirely from the source and replace them with the bare function. Minifiers just need to get a little smarter. ;)

**Comment by jacoborus** [comment]
Ok, now I'm pretty lost (maybe lost in translation), help me to clarify how rfx works please.
Is rfx like a js preprocessor that also can work directly in runtime in order to bring all the app specs to a live javascript analizer?

I wrote my example with docs in comments because ternjs is already doing something similar with jsdocs with [acorn](https://github.com/ternjs/acorn) (Esprima could do it too). Also, that removes the need for transpiling the code before using it in production

**Comment by ericelliott** [comment]
rfx is a library intended for use in actual application code. All it does is wrap interfaces with metadata, and a conditional runtime type checking wrapper for functions. The wrapper makes APIs literally self-documenting at runtime, which can be useful in many development contexts.

No transpiler is needed, but could be written and used to strip the wrappers and metadata from interfaces for production use. That could be done by identifying rfx calls and replacing them with the raw, unwrapped interface.

**Comment by jacoborus** [comment]
This is exactly what I need, thank you. Maybe you should add this to the documentation
