### ISSUE TITLE
Integration with JSDoc

### ISSUE THREAD

**Issue by malyzeli** [ericelliott/rfx#24]
Hello @ericelliott!

I was curious if there is any plan or possibility to integrate `rtype` with regular JSDoc comments. The thing is that it feels a bit clumsy, having to wrap all my function declarations in `rfx` call, and IDEs does not really understand it as well. 

I get the point that the added value of `rtype` is providing runtime data, which can't be extracted from a comment, but that could be possibly solved by code preprocessing. 

It could be much easier to read and write, if we are able to add `rtype` notation inside regular JSDoc comment, either using custom tag `@rtype add(a: n, b: n) => Number`, or possibly using regular `@type` - if we are in control of whole codebase and want to use `rtype` globally, preprocessor could be set to treat `@type` as `@rtype` (though I am not sure this second option is a good idea).

Also I believe it would be easier to integrate into IDEs - most of them can already understand JSDoc, so it should be enough extending it to support `@rtype` tag and parse it's value, which is already implemented in `rfx` itself.

This could be entirely optional - JSDoc will be preprocessed into regular `rfx` calls.

Just wanted to share some of my thoughts. ;)

Have a nice day

**Comment by ericelliott** [comment]
I certainly don't object to somebody creating an rtype JSDoc annotation parser, but this is not the right place for it.

While there are people (including me) using rtype annotations for documentation, so far, nobody has built a feature complete rtype parser, let alone dev tools for it.

If you're actively looking for something that works today that you can use for IDE feedback, the best options I know of are Tern.js+JSDoc or VS Code + JSDoc with the ability to evaluate JS code turned on. Under the hood, it uses the TypeScript inference engine, which understands JSDoc.

If you're looking for something that could eventually support rtype, please build it and share the GitHub link.
