### ISSUE TITLE
not an issue - just fyi

### ISSUE THREAD

**Issue by sebilasse** [ericelliott/rfx#4]
What the V8 people are working on:
https://www.sitepen.com/blog/2015/10/08/stronger-javascript/

The [dojo2](http://dojotoolkit.org) compose [proposal](https://docs.google.com/document/d/10i5agK1Ot1eiB_R5JVEVHY41B0rEvjVyeQ1rl50DTdY/edit?pli=1):
https://github.com/dojo/compose

**Comment by ericelliott** [comment]
1. Strong mode is a dead end. Too many of JS's desirable idioms rely on object extension (everything that calls `Object.assign()`, `_.extend()`, `$.extend()`, etc... Not gonna happen as an ES standard.
2. Dead end because it requires the use of `new`, which is [problematic](https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf).

**Comment by ericelliott** [comment]
The [Stamp Specification](https://github.com/stampit-org/stamp-specification) is much better than DOJO compose.

**Comment by sebilasse** [comment]
@ericelliott Appreciate your answer. Very new to this. 
However: Always when I see new things popping up but in many different locations, I think it is good to connect them somehow... So please let me ping @kitsonk @dylans here (maybe they are not aware of this project) ...

**Comment by ericelliott** [comment]
The [Stamp Specification](https://github.com/stampit-org/stamp-specification) is a better place for this discussion. =)

**Comment by kitsonk** [comment]
We were certainly aware of the work by @ericelliott and a lot of his thoughts and reasoning influenced the Dojo compose proposal and @ericelliott has a lot of respect from me and others.  I will take a look at the discussion at stamp specification and see if there is value we can add.  While I don't disagree with `new` being broken, we debated it.  The biggest (albeit self imposed) challenge is that not only are we working within the confines of ECMAScript, we are doing so while trying to make it fit well in TypeScript, which means that it serves some unique design purposes and constraints.

**Comment by sebilasse** [comment]
@ericelliott @kitsonk Respect? without a question, same here – 
how else could I learn JS or TS without (both) of you ? :smiling_imp:
I could not see major differences (better said: conflicts) between Dojo and Stamp ...
However -

> While I don't disagree with new being broken, we debated it.

I thought so much about this issue and it should be debated as public as possible.

> we are doing so while trying to make it fit well in TypeScript, which means that it serves some unique design purposes and constraints.

totally agree and off course I am using dojo compose TS already - e.g. I commented on the [gist](https://gist.github.com/kitsonk/5c16934888547073c530) ("could .mix support arrays ...")
but because of

> Strong mode is a dead end. 

A bit off topic regarding compose but please let me tell what I want to achieve (for @redaktor, a decentralized CMS) and what I think is a missing piece if Strong mode _is_ a dead end regarding e.g. runtime validation and other cool stuff - 
just the $0.02 of a noob who did not find any good tutorial on decentralized inversion of control;
- What I want to achieve - real world example:
  _We_ have the TS class redaktor.text which is our base class for dealing with strings (including stuff like language detection, natural language processing and more) and it accepts one of the types `http://redaktor.xy/core/string` or `http://redaktor.xy/base/text` and responds with `http://redaktor.xy/base/text` and serves a language independent schema at these URIs.
  Now the _User foo_ creates and registers a (let's say JS) class redaktor.text.language which is able to detect the language of a text and needs `http://redaktor.xy/base/text` but responds with a type `http://foo.me/text/language` ...
  Any other _redaktor_ / _redaktor user_ is now aware of that foo's language module is extending redaktor.text but of course it could extend any other module as well.
- What is my solution / wish :
  @kitsonk A supercool thing by your colleague is [JSON Schema](http://json-schema.org) ([including hyperschema](https://brandur.org/elegant-apis)) [ @kriszyp ]
  it was invented a long time ago, it can solve many problems, it has broad support, great [adoption](https://groups.google.com/forum/#!forum/json-schema) and on top it is language independent (at least it is hard to find any prog.lang. not supporting validation or reasoning somehow) and I can see a great benefit:
  While TS adds no runtime typechecking or validation, 
  ES7 strong might add it or not but just for JS ...
  But if you have **JSON Schema** you have a solid base for validation and reasoning and somehow I would love to have it as a real standard somewhere.
  just btw:
  Now beneath composition APIs so many people are working on e.g. TS to JSON schema projects ...
  If there is a good way to make TS interface matching JSON Schemas you can say so much more about your modules and even build a REST API from that and much more.
  My current approach (started working on it yesterday as CLI) is if you have a JSON hyperschema you can generate things like dojo2 boilerplate together with the interfaces and documentation and class parameters you defined.
  and pps: @ericelliott again: Fighting poverty with code is a wonderful idea and as said could be applied 1:1 to the refugees situation here in germany. But first we are performing well by bringing the Internet to the refugee camps (also thanks to the wonderful initiative freifunk). However: Also one of my next steps...

**Comment by ericelliott** [comment]
@kitsonk I'd be interested in learning why you think `new` is necessary. It seems to me that it's only necessary if you are using classes, which you don't need to use, even in TypeScript. Keep in mind that TypeScript has perfectly good `interface` that can fill in where some people would choose `class`.

`new` is the hook that makes it difficult to escape `class` once you start down the road. When you use it, you close yourself off from a lot of future options.

@sebilasse RE: runtime checks, JSON-Schema is useful, and maybe it could even be generated from TS-style `interface` declarations. Maybe some of  the existing typechecking could even be used by [rtype](https://github.com/ericelliott/rtype), and by extension, rfx, but it's still early days, and there is a lot to decide.

**Comment by kitsonk** [comment]
@ericelliott that is a good point, we had a bit of debate around a pure factory implementation versus a `new`.  In part it mostly was "familiarity" in the wider community and path of least resistance on our part.  It is worth further discussion though, as you are right, we will never be able to escape `new` and close of interesting ways of creating factories down the road.

**Comment by ericelliott** [comment]
> In part it mostly was "familiarity" in the wider community and path of least resistance on our part.

The most common object instantiation pattern in JS is the object literal. The second most common is a factory function. Constructor functions run a distant 3rd place. See ["Common Misconceptions About Inheritance in JavaScript"](https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a).

Everybody who uses JavaScript every day uses factory functions every day, so "familiarity" is not a compelling reason, particularly when it forces your users into [problematic situations](https://medium.com/javascript-scene/inside-the-dev-team-death-spiral-6a7ea255467b).
