### ISSUE TITLE
rtype string parsing – where is it on the roadmap?

### ISSUE THREAD

**Issue by tomek-he-him** [ericelliott/rfx#6]
Hi Eric,

the idea looks great to me! But predicate functions aren’t as easy to scan as an _rtype_ signature. Are you planning to support an rtype string `type` in the foreseeable future?

**Comment by tomek-he-him** [comment]
Wow, I’ve just seen your idea to used tagged template strings (https://github.com/ericelliott/rtype/issues/10#issuecomment-147138172). Wow! Brilliant!

Perhaps we’ll be able to start out with a minimal signature parser. Probably it would be limited to our use case though.

It still depends on some stuff – I’ll let you know if it works out.

**Comment by ericelliott** [comment]
The road map is in the [README](https://github.com/ericelliott/rfx#status---developer-preview).

This support is going to come from the [rtype repo](https://github.com/ericelliott/rtype). I believe @troutowicz  was interested in taking a crack at a parser.

**Comment by tomek-he-him** [comment]
:+1: Thanks for clearing this up!

**Comment by tomek-he-him** [comment]
> Perhaps we’ll be able to start out with a minimal signature parser.

By the way, I meant that I could help if things go well. I’ll keep you updated!

**Comment by ericelliott** [comment]
Cool.. Feel free to give it a shot.

**Comment by tomek-he-him** [comment]
Yup! We will give _rtype_ + _rfx_ a go for our project!

I can help push an _rtype_ parser forward a bit once we get down to type safety. That’ll probably be in December.

**Comment by ericelliott** [comment]
Cool. Thanks for the great feedback so far!
