### ISSUE TITLE
Custom metadata?

### ISSUE THREAD

**Issue by tomek-he-him** [ericelliott/rfx#9]
Hi!

When making larger systems I often found myself introducing my own taxonomies as custom _jsDoc_ tags.

For example I’m working on a collection of style libraries written in JS – every CSS class is a function. I introduced a custom `@class-name` tag to help me automatically generate docs. Is there such a thing in _rfx_?

Perhaps – if we followed my suggestion in https://github.com/ericelliott/rfx/issues/8#issuecomment-156470381 – the `doc` object could take a `summary`, `description` and any other custom property (perhaps beginning or ending with `_` for API future-proofing).

Or perhaps _rfx_ could take a `meta` option which would consist only of custom properties?

**Comment by ericelliott** [comment]
rfx will pass through any extra props you add to the options object. I'd namespace those extras, for future compat reasons. =)

**Comment by ericelliott** [comment]
If you'd like to add some docs about this, I'm open to a PR.

**Comment by tomek-he-him** [comment]
:+1:

Is `meta` a good namespace then?

**Comment by ericelliott** [comment]
No, I mean your own namespace, similar to jQuery plugins. Typically they only occupy a single key on the jQuery prototype, named after the plugin.

In the case of stamps, we use a stamp descriptor attached to a method called `compose`. In this case, `compose` is the namespace used to attach the stamp metadata to fx:

``` js
const myStamp = rfx({
  name: 'interfaceName',
  doc: `some docs`,
  compose: stampDescriptor,
  fn: myFn
});
```

**Comment by tomek-he-him** [comment]
Alright, I get it now.

There’s only one red light flashing in the back of my head. Strictly speaking any release of _rfx_ which takes a new option would be a breaking change.

But perhaps that’s not much of a problem – perhaps we’ll only ever want three or four options there and won’t need to update the signature that often (or even not at all).

**Comment by ericelliott** [comment]
> Strictly speaking any release of rfx which takes a new option would be a breaking change.

Yes. I think that's OK. I expect we may want to extend rfx in the future, but I'm OK with breaking changes when necessary.

This isn't the JavaScript specification. We can break things. =)
